/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  landingSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],

};

export default sidebars;
