name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deployment-staging
  workflow_run:
    workflows: ["Sync main and dev with staging branch"]
    types:
      - completed
  
  workflow_dispatch:  # Allow manual re-run from Actions tab

jobs:
  build:
    if: ${{github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Build Docusaurus
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git # Setup user info and origin url so push will succeed
        run: |
          git config --global user.name 'Actions: Generate MKDocs Website'
          git config --global user.email 'actions-generate-mkdocs-website@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      
      - name: Switch to staging branch
        run: git switch deployment-staging

      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build

      - name: Replace build artifacts
        run: |
          touch ../TEMP
          mv ./build ../TEMP/docs
          git switch gh-pages
          rm -rf ./docs/
          mv ../TEMP/docs ./docs


      - name: Push new source
        run: |
          git add deployed-source/*
          git commit -m "Action: Move pages src to staging dir"
          git push

  deploy:
    if: ${{false && github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
