name: Sync dev with staging branch

on:
    workflow_run:
        workflows: ["Test deployment to dev", "Test deployment to main"]
    
    workflow_dispatch:  # Allow manual re-run from Actions tab


jobs:
    push-from-main:
        name: Push changes from main
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Push versioned docs from main
              run: |
                git switch deployment-staging
                